name: CI

on: [push]

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
            - name: Install dependencies
              run: composer install
            - name: PHPCSFixer check
              run: composer check-style
    phpunit:
        strategy:
            matrix:
                php_version: [8.1, 8.2]
                dependency_version: ["highest", "lowest"]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP environment
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php_version }}
                  coverage: xdebug
            - name: Install dependencies
              uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix.dependency_version }}
            - name: PHPUnit check
              run: ./vendor/bin/phpunit --coverage-text
